package com.doer.testkit;

import io.restassured.path.json.JsonPath;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * A test that works in its own folder: {@link Toolchain} and {@link Sources} bound to {@link #getWorkspace()}. The
 * test class gives the folder, usually with {@code @TempDir(factory = Workspaces.class, cleanup = NEVER)}: per test
 * method (an instance field), or per class (a static field, with {@code @TestInstance(PER_CLASS)} so that
 * {@code @BeforeAll} can use the default methods). See {@link Workspaces}.
 *
 * <pre>
 * &lt;workspace&gt;/
 *     Doer1.java, Main.java, ...   sources, flat (javac does not require folders to match packages)
 *     classes/demo/test/*.class    compiled classes, by package
 *     classes/com/doer/generated/  _GeneratedDoerService.java, doer.json, doer.dot, *.sql
 *     javac-*.txt, java-*.txt      command, stdout and stderr of each run
 * </pre>
 */
public interface InWorkspace {

    Path getWorkspace();

    /** Writes the source file (path is relative to the workspace). */
    default void writeSource(String path, String code) throws IOException {
        Sources.write(getWorkspace(), path, code);
    }

    /** Copies a folder of test resources (for example {@code e2e/transitsims}) into the folder of the workspace. */
    default void copySources(String resourceFolder, String path) throws IOException {
        Sources.copyResources(resourceFolder, getWorkspace().resolve(path));
    }

    /** Paths of all .java files of the workspace, relative to it. */
    default String[] javaFiles() throws IOException {
        return Sources.javaFiles(getWorkspace()).toArray(String[]::new);
    }

    /** Compiles the files with DoerProcessor into the classes folder; the output is kept in javac-*.txt. */
    default RunResult javac(String... optionsAndFiles) throws Exception {
        return Toolchain.javac(getWorkspace(), "javac", Toolchain.compileClasspath(), "classes", optionsAndFiles);
    }

    /** Runs the class compiled into the classes folder; the output is kept in java-*.txt. */
    default RunResult java(String mainClass) throws Exception {
        return Toolchain.java(getWorkspace(), Toolchain.runClasspath("classes"), mainClass);
    }

    /** Runs mvn in batch mode; the output is kept in {@code <logName>-*.txt}. */
    default RunResult mvn(String logName, String... args) throws Exception {
        return Toolchain.mvn(getWorkspace(), logName, args);
    }

    /** File generated by DoerProcessor (compiled by {@link #javac}). */
    default Path generated(String name) {
        return getWorkspace().resolve("classes/com/doer/generated").resolve(name);
    }

    default String generatedService() throws IOException {
        return Files.readString(generated("_GeneratedDoerService.java"));
    }

    default JsonPath doerJson() {
        return JsonPath.from(generated("doer.json").toFile());
    }
}
