package com.doer;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.io.CleanupMode.NEVER;

import com.doer.testkit.Postgres;
import com.doer.testkit.Sources;
import com.doer.testkit.Sql;
import com.doer.testkit.Toolchain;
import com.doer.testkit.Workspaces;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Duration;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.Callable;
import java.util.regex.Pattern;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * SQL of DoerService on the schema generated by DoerProcessor: CreateSchema.sql, CreateIndexes.sql and
 * SelectTasks.sql are generated by javac in {@code @BeforeAll}. Only the SQL is tested here: the service has no
 * transactions (every statement runs in autocommit), transactions and coordination are tested by the E2E suite
 * (TransactionsE2E, CoordinatedUpdateE2E).
 */
public class DoerServiceJdbcITCase {

    /**
     * Two domains. SelectTasks.sql has 5 LIMIT parameters: orders asap (NEW, PAID), orders delayed 2m (SHIPPED),
     * orders failing (retry 20s), payments asap (CHARGE), payments failing (default retry).
     */
    static final String ORDERS = """
            package demo.jdbc;
            import com.doer.*;
            @ConcurrencyGroup("a_orders")
            public class Orders {
                @AcceptStatus("NEW")
                @AcceptStatus("PAID")
                @AcceptStatus(value = "SHIPPED", delay = "2m")
                @RetryPolicy(interval = "20s")
                public void process(Task task) {
                    task.setStatus("DONE");
                }
            }
            """;
    static final String PAYMENTS = """
            package demo.jdbc;
            import com.doer.*;
            @ConcurrencyGroup("b_payments")
            public class Payments {
                @AcceptStatus("CHARGE")
                public void charge(Task task) {
                    task.setStatus("PAID");
                }
            }
            """;

    @TempDir(factory = Workspaces.class, cleanup = NEVER)
    static Path workspace;

    /** Folder with the files generated by DoerProcessor. */
    static Path generated;

    TstJdbcService service;

    @BeforeAll
    static void generateAndCreateSchema() throws Exception {
        Sources.write(workspace, "Orders.java", ORDERS);
        Sources.write(workspace, "Payments.java", PAYMENTS);
        Toolchain.javac(workspace, "javac", Toolchain.compileClasspath(), "classes", "Orders.java", "Payments.java")
                .assertStatus(0);
        generated = workspace.resolve("classes/com/doer/generated");

        try (Connection con = Postgres.dataSource().getConnection(); Statement st = con.createStatement()) {
            st.execute(Files.readString(generated.resolve("CreateSchema.sql")));
            st.execute(Files.readString(generated.resolve("CreateIndexes.sql")));
        }
    }

    @BeforeEach
    void init() {
        Sql.update(Postgres.dataSource(), "DELETE FROM task_logs");
        Sql.update(Postgres.dataSource(), "DELETE FROM tasks");
        service = new TstJdbcService();
    }

    @Test
    void generateId__should_return_new_ids() throws Exception {
        long id1 = service.generateId();
        long id2 = service.generateId();

        assertTrue(id1 >= 1000);
        assertTrue(id2 > id1);
    }

    @Test
    void insert__should_write_task() throws Exception {
        Task task = new Task();
        task.setStatus("NEW");
        task.setInProgress(true);
        Instant failingSince = Instant.now().truncatedTo(ChronoUnit.MILLIS);
        task.setFailingSince(failingSince);

        service.insert(task);

        assertNotNull(task.getId());
        assertNotNull(task.getCreated());
        assertEquals(task.getCreated(), task.getModified());
        assertEquals(0, task.getVersion());
        Task dbTask = service.loadTask(task.getId());
        assertEquals("NEW", dbTask.getStatus());
        assertTrue(dbTask.isInProgress());
        assertEquals(failingSince, dbTask.getFailingSince());
        assertEquals(task.getCreated(), dbTask.getCreated());
        assertEquals(task.getModified(), dbTask.getModified());
        assertEquals(0, dbTask.getVersion());
    }

    @Test
    void insert__should_reject_status_longer_than_50_characters() throws Exception {
        Task task = new Task();
        task.setStatus("S".repeat(50));
        service.insert(task);

        Task tooLong = new Task();
        tooLong.setStatus("S".repeat(51));

        assertThrows(SQLException.class, () -> service.insert(tooLong));
    }

    @Test
    void loadTask__should_read_all_columns() throws Exception {
        long id = Sql.selectLong(Postgres.dataSource(), "INSERT INTO tasks (created, modified, status, "
                + "in_progress, failing_since, version) VALUES ('2026-01-02T03:04:05.123456Z', "
                + "'2026-01-03T03:04:05Z', 'PAID', TRUE, '2026-01-04T03:04:05Z', 7) RETURNING id");

        Task task = service.loadTask(id);

        assertEquals(id, task.getId());
        assertEquals(Instant.parse("2026-01-02T03:04:05.123456Z"), task.getCreated());
        assertEquals(Instant.parse("2026-01-03T03:04:05Z"), task.getModified());
        assertEquals("PAID", task.getStatus());
        assertTrue(task.isInProgress());
        assertEquals(Instant.parse("2026-01-04T03:04:05Z"), task.getFailingSince());
        assertEquals(7, task.getVersion());
    }

    @Test
    void loadTask__should_return_null_for_missing_task() throws Exception {
        assertNull(service.loadTask(9839892L));
    }

    @Test
    void loadTasks__should_return_existing_tasks_once() throws Exception {
        long id1 = insertTask("NEW", false, false, Duration.ZERO);
        long id2 = insertTask("PAID", false, false, Duration.ZERO);

        Map<Long, Task> result = service.loadTasks(Arrays.asList(id1, id2, id1, 9839892L));

        assertEquals(Set.of(id1, id2), result.keySet());
        assertEquals("NEW", result.get(id1).getStatus());
        assertEquals("PAID", result.get(id2).getStatus());
    }

    @Test
    void loadTasks__should_return_empty_map_for_no_ids() throws Exception {
        insertTask("NEW", false, false, Duration.ZERO);

        assertTrue(service.loadTasks(Collections.emptyList()).isEmpty());
        assertTrue(service.loadTasks(Collections.singleton(null)).isEmpty());
    }

    @Test
    void updateAndBumpVersion__should_update_task() throws Exception {
        long id = insertTask("NEW", false, false, Duration.ofMinutes(1));
        Sql.update(Postgres.dataSource(), "UPDATE tasks SET version = 3 WHERE id = " + id);
        Task task = service.loadTask(id);
        Instant oldModified = task.getModified();
        Instant failingSince = Instant.now().truncatedTo(ChronoUnit.MILLIS);
        task.setStatus("PAID");
        task.setInProgress(true);
        task.setFailingSince(failingSince);

        assertTrue(service.updateAndBumpVersion(task));

        assertEquals(4, task.getVersion());
        assertTrue(task.getModified().isAfter(oldModified));
        Task dbTask = service.loadTask(id);
        assertEquals("PAID", dbTask.getStatus());
        assertTrue(dbTask.isInProgress());
        assertEquals(failingSince, dbTask.getFailingSince());
        assertEquals(4, dbTask.getVersion());
        assertEquals(task.getModified(), dbTask.getModified());
        assertEquals(task.getCreated(), dbTask.getCreated());
    }

    @Test
    void updateAndBumpVersion__should_not_update_stale_version() throws Exception {
        long id = insertTask("NEW", false, false, Duration.ZERO);
        Task staleCopy = service.loadTask(id);
        Sql.update(Postgres.dataSource(),
                "UPDATE tasks SET status = 'PAID', version = version + 1 WHERE id = " + id);
        staleCopy.setStatus("SHIPPED");

        assertFalse(service.updateAndBumpVersion(staleCopy));

        assertEquals(0, staleCopy.getVersion());
        Task dbTask = service.loadTask(id);
        assertEquals("PAID", dbTask.getStatus());
        assertEquals(1, dbTask.getVersion());
    }

    @Test
    void selectTaskForUpdate__should_select_in_progress_task_only_when_allowed() throws Exception {
        long inProgress = insertTask("NEW", true, false, Duration.ZERO);
        long idle = insertTask("NEW", false, false, Duration.ZERO);

        assertEquals(inProgress, service.selectTaskForUpdate(inProgress, true).getId());
        assertNull(service.selectTaskForUpdate(inProgress, false));
        assertEquals(idle, service.selectTaskForUpdate(idle, true).getId());
        assertEquals(idle, service.selectTaskForUpdate(idle, false).getId());
        assertNull(service.selectTaskForUpdate(9839892L, true));
        assertNull(service.selectTaskForUpdate(9839892L, false));
    }

    @Test
    void loadTasksFromDatabase__should_have_limit_parameter_per_queue() throws Exception {
        long count = Pattern.compile("LIMIT \\?").matcher(service.readSelectTasksSql()).results().count();

        assertEquals(5, count);
    }

    @Test
    void loadTasksFromDatabase__should_select_tasks_for_each_queue() throws Exception {
        // orders asap: by created, limit 2
        long new30 = insertTask("NEW", false, false, Duration.ofSeconds(30));
        long paid20 = insertTask("PAID", false, false, Duration.ofSeconds(20));
        insertTask("NEW", false, false, Duration.ofSeconds(10));
        // orders delayed: by modified, limit 1
        long shipped50 = insertTask("SHIPPED", false, false, Duration.ofSeconds(50));
        insertTask("SHIPPED", false, false, Duration.ofSeconds(40));
        // orders failing: by modified, limit 1
        insertTask("NEW", false, true, Duration.ofSeconds(5));
        long failingShipped15 = insertTask("SHIPPED", false, true, Duration.ofSeconds(15));
        // payments asap and failing: limit 1 each
        long charge = insertTask("CHARGE", false, false, Duration.ZERO);
        long failingCharge = insertTask("CHARGE", false, true, Duration.ZERO);
        // in progress: always, whatever the status
        long inProgressNew = insertTask("NEW", true, false, Duration.ofSeconds(100));
        long inProgressUnknown = insertTask("UNKNOWN", true, false, Duration.ZERO);
        // not accepted by any doer method
        insertTask("UNKNOWN", false, false, Duration.ofSeconds(100));
        insertTask(null, false, false, Duration.ofSeconds(100));

        List<Task> tasks = service.loadTasksFromDatabase(Arrays.asList(2, 1, 1, 1, 1));

        // Postgres returns UNION ALL results in the order of the selects
        assertEquals(Arrays.asList(new30, paid20, shipped50, failingShipped15, charge, failingCharge),
                tasks.subList(0, 6).stream().map(Task::getId).toList());
        assertEquals(Set.of(inProgressNew, inProgressUnknown),
                Set.copyOf(tasks.subList(6, tasks.size()).stream().map(Task::getId).toList()));
        assertEquals(8, tasks.size());
    }

    @Test
    void resetStalledInProgressTasks__should_reset_only_stalled_tasks() throws Exception {
        long stalled = insertTask("NEW", true, false, Duration.ofHours(3));
        long running = insertTask("PAID", true, false, Duration.ofMinutes(10));
        long idle = insertTask("SHIPPED", false, false, Duration.ofHours(3));
        Instant stalledModified = service.loadTask(stalled).getModified();

        int reset = service.resetStalledInProgressTasks(Duration.ofHours(2));

        assertEquals(1, reset);
        Task stalledTask = service.loadTask(stalled);
        assertFalse(stalledTask.isInProgress());
        assertEquals("NEW", stalledTask.getStatus());
        assertEquals(1, stalledTask.getVersion());
        assertTrue(stalledTask.getModified().isAfter(stalledModified));
        assertEquals(List.of(new TaskLog(stalled, "NEW", "NEW", "DoerService", "resetStalledInProgressTasks", null,
                "StalledTaskReset", null)), taskLogs(stalled));
        Task runningTask = service.loadTask(running);
        assertTrue(runningTask.isInProgress());
        assertEquals(0, runningTask.getVersion());
        assertEquals(0, service.loadTask(idle).getVersion());
        assertEquals(List.of(), taskLogs(running));
        assertEquals(List.of(), taskLogs(idle));
    }

    @Test
    void resetStalledInProgressTasks__should_reject_negative_timeout() {
        assertThrows(IllegalArgumentException.class,
                () -> service.resetStalledInProgressTasks(Duration.ofSeconds(-1)));
    }

    @Test
    void writeTaskLog__should_write_all_columns() throws Exception {
        long logId = service.writeTaskLog(801L, "NEW", "PAID", "Orders", "process", "java.lang.IllegalStateException",
                "{\"e1\": \"Exception\"}", 15);

        assertTrue(logId >= 1000);
        assertEquals(List.of(new TaskLog(801L, "NEW", "PAID", "Orders", "process", 15L,
                "java.lang.IllegalStateException", "{\"e1\": \"Exception\"}")), taskLogs(801L));
    }

    @Test
    void writeTaskLog__should_write_nulls() throws Exception {
        service.writeTaskLog(802L, "NEW", null, "Orders", "process", null, null, null);

        assertEquals(List.of(new TaskLog(802L, "NEW", null, "Orders", "process", null, null, null)),
                taskLogs(802L));
    }

    @Test
    void createIndexes__should_create_indexes_for_generated_statuses() {
        assertEquals("tasks_delayed_idx,tasks_failing_idx,tasks_in_progress_idx,tasks_pkey,tasks_status_idx",
                Sql.selectString(Postgres.dataSource(), "SELECT string_agg(indexname, ',' ORDER BY indexname) "
                        + "FROM pg_indexes WHERE tablename = 'tasks'"));
        assertTrue(Sql.selectString(Postgres.dataSource(),
                "SELECT indexdef FROM pg_indexes WHERE indexname = 'tasks_delayed_idx'").contains("'SHIPPED'"));
    }

    /** Inserts a task created and modified {@code age} ago; a failing task fails since now. */
    long insertTask(String status, boolean inProgress, boolean failing, Duration age) throws SQLException {
        String sql = "INSERT INTO tasks (status, in_progress, failing_since, created, modified) "
                + "VALUES (?, ?, CASE WHEN ? THEN now() END, now() - make_interval(secs => ?), "
                + "now() - make_interval(secs => ?)) RETURNING id";
        try (Connection con = Postgres.dataSource().getConnection();
                PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setString(1, status);
            pst.setBoolean(2, inProgress);
            pst.setBoolean(3, failing);
            pst.setDouble(4, age.toSeconds());
            pst.setDouble(5, age.toSeconds());
            try (ResultSet rs = pst.executeQuery()) {
                rs.next();
                return rs.getLong(1);
            }
        }
    }

    record TaskLog(long taskId, String initialStatus, String finalStatus, String className, String methodName,
            Long durationMs, String exceptionType, String extraJson) {
    }

    /** The task_logs rows of the task, in the order they were written. */
    List<TaskLog> taskLogs(long taskId) throws SQLException {
        String sql = "SELECT task_id, initial_status, final_status, class_name, method_name, duration_ms, "
                + "exception_type, extra_json::text FROM task_logs WHERE task_id = ? ORDER BY id";
        List<TaskLog> logs = new ArrayList<>();
        try (Connection con = Postgres.dataSource().getConnection();
                PreparedStatement pst = con.prepareStatement(sql)) {
            pst.setLong(1, taskId);
            try (ResultSet rs = pst.executeQuery()) {
                while (rs.next()) {
                    logs.add(new TaskLog(rs.getLong(1), rs.getString(2), rs.getString(3), rs.getString(4),
                            rs.getString(5), rs.getObject(6, Long.class), rs.getString(7), rs.getString(8)));
                }
            }
        }
        return logs;
    }

    /** DoerService with the generated SelectTasks.sql and without transactions. */
    static class TstJdbcService extends DoerService {

        TstJdbcService() {
            setDataSource(Postgres.dataSource());
            setSelfReference(this);
        }

        @Override
        protected String readSelectTasksSql() throws IOException {
            return Files.readString(generated.resolve("SelectTasks.sql"));
        }

        @Override
        public void runInTransaction(Callable<Object> code) {
            throw new UnsupportedOperationException("SQL only: transactions are tested by the E2E suite");
        }

        @Override
        public void runTask(Task task) {
            throw new UnsupportedOperationException();
        }

        @Override
        protected Object _load(Task task, Class<?> type) {
            throw new UnsupportedOperationException();
        }

        @Override
        protected void _save(Task task, Class<?> type, Object data) {
            throw new UnsupportedOperationException();
        }

        @Override
        public String createExtraJson(Task task, Exception exception) {
            throw new UnsupportedOperationException();
        }
    }
}
