package com.doer;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.containsString;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Set;
import io.restassured.path.json.JsonPath;
import org.junit.jupiter.api.Test;

/** Code generated by DoerProcessor: generation succeeds, the generated code works as expected. */
public class GeneratorITCase extends GeneratorTestBase {

    @Test
    void AcceptStatus__should_call_doer_method() throws Exception {
        writeSource("Doer1.java", """
                package demo.test;
                import com.doer.*;
                public class Doer1 {
                    @AcceptStatus("A")
                    public void method1(Task task) {
                        System.out.println("Doer1 method1 called");
                    }
                }
                """);
        writeSource("TestDoerService.java", TEST_DOER_SERVICE);
        writeSource("Main.java", """
                package demo.test;
                import com.doer.*;
                public class Main {
                    public static void main(String[] args) throws Exception {
                        System.out.println("Main method called");
                        var doer = new TestDoerService();
                        doer._inject_doer1(new Doer1());
                        Task task = new Task();
                        task.setStatus("A");
                        doer.runTask(task);
                    }
                }
                """);
        javac("Doer1.java", "TestDoerService.java", "Main.java").assertStatus(0);

        var result = java("demo.test.Main").assertStatus(0);

        assertEquals("""
                Main method called
                Doer1 method1 called
                """, result.stdOut());
    }

    @Test
    void AcceptStatus__should_call_one_doer_method_for_several_statuses() throws Exception {
        writeSource("Doer1.java", """
                package demo.test;
                import com.doer.*;
                public class Doer1 {
                    @AcceptStatus("A")
                    @AcceptStatus("B")
                    public void method2(Task task) {
                        System.out.println("---" + task.getStatus() + "---");
                    }
                }
                """);
        writeSource("TestDoerService.java", TEST_DOER_SERVICE);
        writeSource("Main.java", """
                package demo.test;
                import com.doer.*;
                public class Main {
                    public static void main(String[] args) throws Exception {
                        System.out.println("---main---");
                        var doer = new TestDoerService();
                        doer._inject_doer1(new Doer1());
                        Task task = new Task();
                        task.setStatus("A");
                        doer.runTask(task);
                        task.setStatus("B");
                        doer.runTask(task);
                    }
                }
                """);
        javac("Doer1.java", "TestDoerService.java", "Main.java").assertStatus(0);

        var result = java("demo.test.Main").assertStatus(0);

        assertEquals("""
                ---main---
                ---A---
                ---B---
                """, result.stdOut());
    }

    @Test
    void RetryPolicy__should_default_to_1_day() throws Exception {
        writeSource("Orders.java", """
                package demo.test;
                import com.doer.*;
                public class Orders {
                    @AcceptStatus("A")
                    public void accept(Task task) {}
                }
                """);

        var result = javac("Orders.java").assertStatus(0);

        assertEquals("", result.stdErr());
        assertThat(generatedService(), containsString("Duration.ofDays(1), null);"));
    }

    @Test
    void ConcurrencyGroup__should_list_domains_in_doer_json() throws Exception {
        writeSource("Orders.java", """
                package demo.test;
                import com.doer.*;
                @ConcurrencyGroup("orders")
                @ConcurrencyLimit(5)
                public class Orders {
                    @AcceptStatus("A")
                    @RetryPolicy(interval = "5m")
                    public void accept(Task task) {}
                }
                """);
        writeSource("Payments.java", """
                package demo.test;
                import com.doer.*;
                public class Payments {
                    @ConcurrencyGroup("orders")
                    @AcceptStatus("B")
                    @RetryPolicy(interval = "5s", duration = "10 min", fallbackStatus = "Payment failed")
                    public void pay(Task task) {}

                    @AcceptStatus("C")
                    @RetryPolicy(interval = "5m")
                    public void refund(Task task) {}
                }
                """);
        writeSource("Shipping.java", """
                package demo.test;
                import com.doer.*;
                public class Shipping {
                    @ConcurrencyGroup("demo.test.Payments")
                    @AcceptStatus("D")
                    @RetryPolicy(interval = "5m")
                    public void ship(Task task) {}

                    @AcceptStatus("E")
                    @RetryPolicy(interval = "5m")
                    public void track(Task task) {}
                }
                """);

        javac("Orders.java", "Payments.java", "Shipping.java").assertStatus(0);

        JsonPath json = doerJson();
        assertEquals(List.of("demo.test.Payments", "demo.test.Shipping", "orders"), json.getList("domains.name"));
        assertEquals(List.of(2, 2, 5), json.getList("domains.limit"));
        assertEquals(List.of(false, true, false), json.getList("domains.implicit"));
        assertEquals(List.of("orders", "orders", "demo.test.Payments", "demo.test.Payments", "demo.test.Shipping"),
                json.getList("doer_methods.domain"));
        assertEquals("5s", json.getString("doer_methods[1].interval"));
        assertEquals("10 min", json.getString("doer_methods[1].duration"));
        assertEquals("Payment failed", json.getString("doer_methods[1].fallback_status"));
    }

    @Test
    void TaskDataLoader__should_load_doer_method_arguments() throws Exception {
        writeSource("Doer1.java", """
                package demo.test;
                import com.doer.*;
                public class Doer1 {
                    @AcceptStatus("A")
                    public void method2(DemoClass data, Task task) {
                        System.out.println("---" + task.getStatus() + "---" + data.name + "---");
                    }
                }
                """);
        writeSource("DemoClass.java", """
                package demo.test;
                public class DemoClass {
                    public String name;
                }
                """);
        writeSource("DemoClassLoader.java", """
                package demo.test;
                import com.doer.*;
                public class DemoClassLoader {
                    @TaskDataLoader
                    public DemoClass loadDemoClass(Task task) {
                        System.out.println("---load-DemoClass-for-" + task.getStatus() + "---");
                        DemoClass c = new DemoClass();
                        c.name = "d1";
                        return c;
                    }
                }
                """);
        writeSource("TestDoerService.java", TEST_DOER_SERVICE);
        writeSource("Main.java", """
                package demo.test;
                import com.doer.*;
                public class Main {
                    public static void main(String[] args) throws Exception {
                        System.out.println("---main---");
                        var doer = new TestDoerService();
                        doer._inject_doer1(new Doer1());
                        doer._inject_demoClassLoader(new DemoClassLoader());
                        Task task = new Task();
                        task.setStatus("A");
                        doer.runTask(task);
                    }
                }
                """);
        javac("Doer1.java", "DemoClass.java", "DemoClassLoader.java", "TestDoerService.java",
                "Main.java").assertStatus(0);

        var result = java("demo.test.Main").assertStatus(0);

        assertEquals("""
                ---main---
                ---load-DemoClass-for-A---
                ---A---d1---
                """, result.stdOut());
    }

    @Test
    void TaskDataSaver__should_save_doer_method_arguments() throws Exception {
        writeSource("TestDoerService.java", TEST_DOER_SERVICE);
        writeSource("Main.java", """
                package demo.test;
                import com.doer.*;
                public class Main {
                    public static void main(String[] args) throws Exception {
                        System.out.println("---main---");
                        var doer = new TestDoerService();
                        doer._inject_main(new Main());
                        Task task = new Task();
                        task.setStatus("A");
                        doer.runTask(task);
                    }
                    @AcceptStatus("A")
                    public void doerMethod(Task task, String data) {
                        System.out.println("---" + task.getStatus() + "---" + data + "---");
                    }
                    @TaskDataLoader
                    public String loaderMethod(Task task) {
                        System.out.println("---load-String-for-" + task.getStatus() + "---");
                        return "d2";
                    }
                    @TaskDataSaver
                    public void saverMethod(Task task, String data) {
                        System.out.println("---save-String-for-" + task.getStatus() + "---" + data + "---");
                    }
                }
                """);
        javac("TestDoerService.java", "Main.java").assertStatus(0);

        var result = java("demo.test.Main").assertStatus(0);

        assertEquals("""
                ---main---
                ---load-String-for-A---
                ---A---d2---
                ---save-String-for-A---d2---
                """, result.stdOut());
    }

    /**
     * Keep the anonymous subclass of _GeneratedDoerService assigned to var: no other test has it. Main.java refers to
     * the class that DoerProcessor generates in the same javac run, calls its protected _load/_save, and through var
     * calls tst_load() and tst_save(), which only the anonymous class declares. Other tests use the named
     * TestDoerService instead.
     *
     * <p>_load of a type without @TaskDataLoader throws IllegalArgumentException; _save of a type without
     * @TaskDataSaver does nothing.
     */
    @Test
    void task_data__should_be_loaded_and_saved_by_type() throws Exception {
        writeSource("Main.java", """
                package demo.test;
                import com.doer.*;
                import com.doer.generated._GeneratedDoerService;
                public class Main {
                    public static void main(String[] args) throws Exception {
                        var doer = new _GeneratedDoerService() {
                            Object tst_load(Task task, Class<?> type) throws Exception {
                                return _load(task, type);
                            }
                            void tst_save(Task task, Class<?> type, Object data) throws Exception {
                                _save(task, type, data);
                            }
                        };
                        doer._inject_main(new Main());
                        Task task = new Task();
                        task.setStatus("A");

                        Object data = doer.tst_load(task, String.class);
                        System.out.println("---loaded-" + data + "---");
                        doer.tst_save(task, String.class, data);

                        try {
                            doer.tst_load(task, Integer.class);
                            System.out.println("---Integer-loaded---");
                        } catch (IllegalArgumentException e) {
                            System.out.println("---" + e.getMessage() + "---");
                        }
                        doer.tst_save(task, Integer.class, 42);
                        System.out.println("---Integer-save-ignored---");
                    }
                    @TaskDataLoader
                    public String loaderMethod(Task task) {
                        System.out.println("---load-String-for-" + task.getStatus() + "---");
                        return "d2";
                    }
                    @TaskDataSaver
                    public void saverMethod(Task task, String data) {
                        System.out.println("---save-String-" + data + "---");
                    }
                }
                """);
        javac("Main.java").assertStatus(0);

        var result = java("demo.test.Main").assertStatus(0);

        assertEquals("""
                ---load-String-for-A---
                ---loaded-d2---
                ---save-String-d2---
                ---No @TaskDataLoader for java.lang.Integer---
                ---Integer-save-ignored---
                """, result.stdOut());
    }

    @Test
    void task_data__should_support_nested_classes() throws Exception {
        writeSource("Orders.java", """
                package demo.test;
                import com.doer.*;
                public class Orders {
                    public record CancellationContext(String reason) {}

                    @AcceptStatus("A")
                    public void cancel(Task task, CancellationContext context) {
                        System.out.println("---cancel-" + context.reason() + "---");
                    }

                    @TaskDataLoader
                    public CancellationContext loadContext(Task task) {
                        System.out.println("---load-CancellationContext---");
                        return new CancellationContext("late");
                    }

                    @TaskDataSaver
                    public void saveContext(Task task, CancellationContext context) {
                        System.out.println("---save-CancellationContext-" + context.reason() + "---");
                    }
                }
                """);
        writeSource("TestDoerService.java", TEST_DOER_SERVICE);
        writeSource("Main.java", """
                package demo.test;
                import com.doer.*;
                public class Main {
                    public static void main(String[] args) throws Exception {
                        var doer = new TestDoerService();
                        doer._inject_orders(new Orders());
                        Task task = new Task();
                        task.setStatus("A");
                        doer.runTask(task);
                    }
                }
                """);
        javac("Orders.java", "TestDoerService.java", "Main.java").assertStatus(0);

        var result = java("demo.test.Main").assertStatus(0);

        assertEquals("""
                ---load-CancellationContext---
                ---cancel-late---
                ---save-CancellationContext-late---
                """, result.stdOut());
        String service = generatedService();
        assertThat(service, containsString("import demo.test.Orders.CancellationContext;"));
        assertThat(service, containsString("orders.cancel(task, (CancellationContext)args[1]);"));
    }

    /**
     * demo.data.Task and demo.data.String have the simple names of com.doer.Task and java.lang.String, which the
     * generated service uses, so it must refer to them by full names.
     */
    @Test
    void task_data__should_use_full_names_for_taken_short_names() throws Exception {
        writeSource("Task.java", """
                package demo.data;
                public class Task {
                    public final java.lang.String value;
                    public Task(java.lang.String value) {
                        this.value = value;
                    }
                }
                """);
        writeSource("String.java", """
                package demo.data;
                public class String {
                    public final java.lang.String value;
                    public String(java.lang.String value) {
                        this.value = value;
                    }
                }
                """);
        writeSource("Orders.java", """
                package demo.test;
                import com.doer.*;
                public class Orders {
                    @AcceptStatus("A")
                    public void accept(Task task, demo.data.Task data, demo.data.String text, String plain) {
                        System.out.println("accept " + data.value + ", " + text.value + ", " + plain);
                    }

                    @TaskDataLoader
                    public String loadPlain(Task task) {
                        System.out.println("load java.lang.String");
                        return "plain-1";
                    }

                    @TaskDataLoader
                    public demo.data.String loadText(Task task) {
                        System.out.println("load demo.data.String");
                        return new demo.data.String("text-1");
                    }

                    @TaskDataLoader
                    public demo.data.Task loadData(Task task) {
                        System.out.println("load demo.data.Task");
                        return new demo.data.Task("data-1");
                    }

                    @TaskDataSaver
                    public void saveData(Task task, demo.data.Task data) {
                        System.out.println("save demo.data.Task " + data.value);
                    }

                    @TaskDataSaver
                    public void savePlain(Task task, String plain) {
                        System.out.println("save java.lang.String " + plain);
                    }

                    @TaskDataSaver
                    public void saveText(Task task, demo.data.String text) {
                        System.out.println("save demo.data.String " + text.value);
                    }
                }
                """);
        writeSource("TestDoerService.java", TEST_DOER_SERVICE);
        writeSource("Main.java", """
                package demo.test;
                import com.doer.*;
                public class Main {
                    public static void main(String[] args) throws Exception {
                        var doer = new TestDoerService();
                        doer._inject_orders(new Orders());
                        Task task = new Task();
                        task.setStatus("A");

                        System.out.println("--- runTask ---");
                        doer.runTask(task);

                        System.out.println("--- _load and _save by type ---");
                        doer._load(task, demo.data.Task.class);
                        doer._save(task, demo.data.Task.class, new demo.data.Task("data-2"));
                        doer._load(task, demo.data.String.class);
                        doer._save(task, demo.data.String.class, new demo.data.String("text-2"));
                        doer._load(task, java.lang.String.class);
                        doer._save(task, java.lang.String.class, "plain-2");
                        try {
                            doer._load(task, com.doer.Task.class);
                        } catch (IllegalArgumentException e) {
                            System.out.println(e.getMessage());
                        }
                    }
                }
                """);
        javac("Orders.java", "Task.java", "String.java", "TestDoerService.java", "Main.java").assertStatus(0);

        var result = java("demo.test.Main").assertStatus(0);

        assertEquals("""
                --- runTask ---
                load demo.data.Task
                load demo.data.String
                load java.lang.String
                accept data-1, text-1, plain-1
                save java.lang.String plain-1
                save demo.data.String text-1
                save demo.data.Task data-1
                --- _load and _save by type ---
                load demo.data.Task
                save demo.data.Task data-2
                load demo.data.String
                save demo.data.String text-2
                load java.lang.String
                save java.lang.String plain-2
                No @TaskDataLoader for com.doer.Task
                """, result.stdOut());
    }

    @Test
    void ExceptionDescriber__should_describe_exception_and_its_cause() throws Exception {
        writeSource("Describers.java", """
                package demo.test;
                import com.doer.*;
                import jakarta.json.JsonObjectBuilder;
                public class Describers {
                    @ExceptionDescriber
                    public void describeException(Task task, Exception ex, JsonObjectBuilder builder) {
                        builder.add("type", ex.getClass().getSimpleName());
                    }
                    @ExceptionDescriber
                    public void describeIllegalState(Task task, IllegalStateException ex, JsonObjectBuilder builder) {
                        builder.add("illegal_state", true);
                    }
                }
                """);
        writeSource("TestDoerService.java", TEST_DOER_SERVICE);
        writeSource("Main.java", """
                package demo.test;
                import com.doer.*;
                import java.io.IOException;
                public class Main {
                    public static void main(String[] args) throws Exception {
                        var doer = new TestDoerService();
                        doer._inject_describers(new Describers());
                        Task task = new Task();
                        System.out.println(doer.createExtraJson(task, new Exception()));
                        System.out.println("---");
                        System.out.println(doer.createExtraJson(task, new IOException("Disk full")));
                        System.out.println("---");
                        System.out.println(doer.createExtraJson(task,
                                new IllegalStateException("Bad state", new IOException("Disk full"))));
                    }
                }
                """);
        javac("Describers.java", "TestDoerService.java", "Main.java").assertStatus(0);

        var result = java("demo.test.Main").assertStatus(0);

        assertEquals("""
                {"type":"Exception"}
                ---
                {
                    "message": "Disk full",
                    "type": "IOException"
                }
                ---
                {
                    "message": "Bad state",
                    "type": "IllegalStateException",
                    "illegal_state": true,
                    "cause": {
                        "message": "Disk full",
                        "type": "IOException"
                    }
                }
                """, result.stdOut());
    }

    @Test
    void setStatus__should_be_found_in_all_statements() throws Exception {
        writeSource("Flamingo.java", """
                package demo.test;
                import java.util.Collections;
                import com.doer.*;
                public class Flamingo {
                    boolean x = false;
                    @AcceptStatus("A1")
                    public void fly(Task task) {
                        task.setStatus("METHOD_S1");
                        if (task.isInProgress()) {
                            task.setStatus("IF_S1");
                        } else {
                            task.setStatus("ELSE_S1");
                        }
                        ((Runnable)() -> task.setStatus("LAMBDA_S1")).run();
                        task.setStatus(task.isInProgress() ? "?_S1" : (x ? "?_S2" : "?_S3"));
                        switch (task.getStatus()) {
                            case "A":
                                task.setStatus("CASE_S1");
                                break;
                            default:
                                task.setStatus("DEFAULT_S1");
                                break;
                        }
                        if(x) {} else {}
                        if(x) {}
                        try {
                            task.setStatus("TRY_S1");
                        } catch (RuntimeException e) {
                            task.setStatus("CATCH_S1");
                        } finally {
                            task.setStatus("FINALLY_S1");
                        }
                        for(String a : Collections.singleton("a")) {
                            task.setStatus("FOREACH_S1");
                        }
                        for(int i = 0; i < 1; i++) {
                            task.setStatus("FOR_S1");
                        }
                        while(x) {
                            task.setStatus("WHILE_S1");
                        }
                        do {
                            task.setStatus("DO_S1");
                        } while(x);
                        synchronized(this) {
                            task.setStatus("SYNCHRONIZED_S1");
                        }
                        switch(task.getStatus()) {}
                    }
                }
                """);

        javac("Flamingo.java").assertStatus(0);

        assertEquals(Set.of("METHOD_S1", "IF_S1", "ELSE_S1", "LAMBDA_S1", "?_S1", "?_S2", "?_S3",
                "CASE_S1", "DEFAULT_S1", "TRY_S1", "CATCH_S1", "FINALLY_S1", "FOREACH_S1", "FOR_S1", "WHILE_S1",
                "DO_S1", "SYNCHRONIZED_S1"),
                Set.copyOf(doerJson().getList("doer_methods[0].emits")));
    }

    @Test
    void setStatus__should_be_found_with_null_status() throws Exception {
        writeSource("Pelican.java", """
                package demo.test;
                import com.doer.*;
                public class Pelican {
                    boolean anything = false;
                    @AcceptStatus("A1")
                    public void fish(Task task) {
                        if (anything) {
                            task.setStatus(null);
                        } else {
                            task.setStatus("Extra to do");
                        }
                    }
                }
                """);

        javac("Pelican.java").assertStatus(0);

        JsonPath json = doerJson();
        assertEquals(List.of("Extra to do"), json.getList("doer_methods[0].emits"));
        assertEquals(Boolean.TRUE, json.get("doer_methods[0].emits_null"));
        assertTrue(Files.isRegularFile(generated("doer.dot")));
    }

    @Test
    void setStatus__should_be_found_in_switch_expressions_and_lambdas() throws Exception {
        writeSource("Heron.java", """
                package demo.test;
                import com.doer.*;
                public class Heron {
                    static final String DONE = "Const field";
                    int n = 1;
                    @AcceptStatus("A1")
                    public void fly(Task task) {
                        final String local = "Const local";
                        switch (task.getStatus()) {
                            case "A" -> task.setStatus("Arrow A");
                            default -> { task.setStatus("Arrow Default"); }
                        }
                        task.setStatus(switch (n) {
                            case 1 -> "Switch 1";
                            case 2 -> n > 0 ? "Switch 2a" : "Switch 2b";
                            default -> {
                                int m = switch (n) { case 3 -> 3; default -> { yield 4; } };
                                yield "Switch Default";
                            }
                        });
                        outer:
                        for (int i = 0; i < 1; i++) {
                            task.setStatus("Labeled");
                            break outer;
                        }
                        run(() -> task.setStatus("Via helper"));
                        task.setStatus(DONE);
                        task.setStatus(Heron.DONE);
                        task.setStatus(local);
                        task.setStatus("Prefix " + n);
                        task.setStatus(String.valueOf(n));
                    }
                    static void run(Runnable r) {
                        r.run();
                    }
                }
                """);

        javac("Heron.java").assertStatus(0);

        assertEquals(List.of("Arrow A", "Arrow Default", "Const field", "Const local", "Labeled", "Switch 1",
                "Switch 2a", "Switch 2b", "Switch Default", "Via helper"),
                doerJson().getList("doer_methods[0].emits"));
    }

    @Test
    void setStatus__should_be_found_with_constants_from_other_classes() throws Exception {
        writeSource("Statuses1.java", """
                package demo.test;
                public interface Statuses1 {
                    String ST1_1 = "ST1_1_value";
                }
                """);
        writeSource("Statuses2.java", """
                package demo.test;
                public abstract class Statuses2 {
                    final public static String ST2_2 = "ST2_2_value";
                }
                """);
        writeSource("Flamingo.java", """
                package demo.test;
                import com.doer.*;
                import static demo.test.Statuses2.*;
                public class Flamingo implements Statuses1 {
                    @AcceptStatus("Z1")
                    public void fly(Task task) {
                        task.setStatus(ST1_1);
                        task.setStatus(ST2_2);
                    }
                }
                """);

        javac("Flamingo.java", "Statuses1.java", "Statuses2.java").assertStatus(0);

        assertEquals(List.of("ST1_1_value", "ST2_2_value"), doerJson().getList("doer_methods[0].emits"));
    }

    @Test
    void doer_json__should_list_delays_loaders_savers_and_describers() throws Exception {
        writeSource("Orders.java", """
                package demo.test;
                import com.doer.*;
                import jakarta.json.JsonObjectBuilder;
                public class Orders {
                    public static class Order {}

                    @AcceptStatus(value = "A", delay = "10 min")
                    @AcceptStatus("B")
                    public void accept(Task task, Order order) {}

                    @TaskDataLoader
                    public Order loadOrder(Task task) {
                        return new Order();
                    }

                    @TaskDataSaver
                    public void saveOrder(Task task, Order order) {}

                    @ExceptionDescriber
                    public void describe(Task task, IllegalStateException e, JsonObjectBuilder builder) {}
                }
                """);

        javac("Orders.java").assertStatus(0);

        String doerJson = Files.readString(generated("doer.json"))
                .replaceFirst("\"generated\": \"[^\"]+\"", "\"generated\": \"<time>\"");
        assertEquals("""
                {
                    "generator": "com.doer.processor.DoerProcessor",
                    "generated": "<time>",
                    "domains": [
                        {"name": "demo.test.Orders", "limit": 2, "implicit": true}
                    ],
                    "doer_methods": [
                        {
                            "domain": "demo.test.Orders",
                            "class": "demo.test.Orders", "method": "accept",
                            "args": ["com.doer.Task", "demo.test.Orders.Order"],
                            "accepts": [
                                {"status": "A", "delay": "10 min"},
                                {"status": "B"}
                            ],
                            "emits": [
                            ]
                        }
                    ],
                    "loaders": [
                        {"type": "demo.test.Orders.Order", "class": "demo.test.Orders", "method": "loadOrder"}
                    ],
                    "savers": [
                        {"type": "demo.test.Orders.Order", "class": "demo.test.Orders", "method": "saveOrder"}
                    ],
                    "exception_describers": [
                        {"type": "java.lang.IllegalStateException", "class": "demo.test.Orders", "method": "describe"}
                    ]
                }
                """, doerJson);
        assertThat(Files.readString(generated("doer.dot")), containsString("label=\"delay 10 min\""));
    }

    @Test
    void car_wash__should_work_when_built_with_javac() throws Exception {
        writeCarWashClasses(workspace);
        writeSource("TestDoerService.java", TEST_DOER_SERVICE);
        String expectedOut = writeCarWashMain(workspace);

        javac("Soap.java",
                "Driver.java",
                "Car.java",
                "test2/Car.java",
                "Washer.java",
                "CarWash.java",
                "Bar.java",
                "CheckIn.java",
                "ExceptionMapper.java",
                "TestDoerService.java",
                "Main.java").assertStatus(0);
        var result = java("demo.test.Main").assertStatus(0);

        System.out.println("--------Generated code (just for reference)-------");
        System.out.println(generatedService());

        assertEquals(expectedOut, result.stdOut());
    }

    @Test
    void car_wash__should_work_when_built_with_maven() throws Exception {
        mvn(workspace, "mvn-archetype", "archetype:generate", "-DgroupId=demo.test", "-DartifactId=my-app",
                "-DarchetypeArtifactId=maven-archetype-quickstart", "-DarchetypeVersion=1.4",
                "-DinteractiveMode=false").assertStatus(0);
        Path appFolder = workspace.resolve("my-app");
        Files.delete(appFolder.resolve("src/test/java/demo/test/AppTest.java"));
        Files.delete(appFolder.resolve("src/main/java/demo/test/App.java"));
        Path srcRoot = appFolder.resolve("src/main/java");
        writeCarWashClasses(srcRoot);
        writeSource(srcRoot, "TestDoerService.java", TEST_DOER_SERVICE);
        String expectedOut = writeCarWashMain(srcRoot);
        String dependencies = """
                  <dependency>
                      <groupId>com.java-doer</groupId>
                      <artifactId>doer</artifactId>
                      <version>%s</version>
                    </dependency>
                    <dependency>
                      <groupId>jakarta.platform</groupId>
                      <artifactId>jakarta.jakartaee-api</artifactId>
                      <version>%s</version>
                    </dependency>
                  </dependencies>
                """.formatted(doerLibVersion, jakartaVersion);
        String plugins = """
                  <plugins>
                      <plugin>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <configuration>
                          <parameters>true</parameters>
                          <annotationProcessorPaths>
                            <path>
                              <groupId>com.java-doer</groupId>
                              <artifactId>doer</artifactId>
                              <version>%s</version>
                            </path>
                          </annotationProcessorPaths>
                        </configuration>
                      </plugin>
                    </plugins>
                  </build>
                """.formatted(doerLibVersion);
        String pom = Files.readString(appFolder.resolve("pom.xml"))
                .replaceAll("<maven.compiler.source>[^<]+</maven.compiler.source>",
                        "<maven.compiler.source>17</maven.compiler.source>")
                .replaceAll("<maven.compiler.target>[^<]+</maven.compiler.target>",
                        "<maven.compiler.target>17</maven.compiler.target>")
                .replace("</dependencies>", dependencies.strip())
                .replace("</build>", plugins.strip());
        Files.writeString(appFolder.resolve("pom.xml"), pom);

        mvn(appFolder, "mvn-package", "package").assertStatus(0);
        var result = mvn(appFolder, "mvn-exec", "-q", "exec:java", "-Dexec.mainClass=demo.test.Main")
                .assertStatus(0);

        assertEquals(expectedOut, result.stdOut());
    }

    /**
     * Classes for testing different allocation of doer methods and loaders and number of parameters.
     *
     * <p>Data objects passed to doer methods:
     * <ul>
     * <li>Soap - loaded but not saved (disposed after doer method call)
     * <li>Driver - loaded from demo.test2.Car and saved to CheckIn
     * <li>Car - loaded from CheckIn, saved in CarWash
     * <li>Washer - loaded from Bar, saved to Bar
     * </ul>
     *
     * <p>Doer methods: CarWash.washTheCar(task, car, washer, soap), Bar.takeACoffe(task, driver).
     *
     * <p>Loaders: CarWash.loadSoap(task), Bar.callFreeWasher(task), demo.test2.Car.inviteDriver(task),
     * CheckIn.takeACar(task).
     *
     * <p>Savers: CarWash.putCarToReadyQueue(task, car), Bar.releaseFreeWasher(task, washer),
     * CheckIn.checkoutDriver(task, driver).
     *
     * <p>Sources are flat in srcRoot, except demo.test2.Car: it is in test2/Car.java, because Car.java is
     * demo.test.Car.
     */
    static void writeCarWashClasses(Path srcRoot) throws Exception {
        writeSource(srcRoot, "Soap.java", """
                package demo.test;
                public class Soap {}
                """);
        writeSource(srcRoot, "Driver.java", """
                package demo.test;
                public class Driver {}
                """);
        writeSource(srcRoot, "Car.java", """
                package demo.test;
                public class Car {}
                """);
        writeSource(srcRoot, "test2/Car.java", """
                package demo.test2;
                import com.doer.*;
                import demo.test.Driver;
                public class Car {
                    @TaskDataLoader
                    public Driver inviteDriver(Task task) {
                        System.out.println(" Inviting driver");
                        return new Driver();
                    }
                }
                """);
        writeSource(srcRoot, "Washer.java", """
                package demo.test;
                public class Washer {}
                """);
        writeSource(srcRoot, "CarWash.java", """
                package demo.test;
                import com.doer.*;
                public class CarWash {
                    @AcceptStatus("Car is ready to be washed")
                    @AcceptStatus("Bus came to the wash")
                    public void washTheCar(Task task, Car car, Washer washer, Soap soap) {
                        System.out.println("  Washing the car (" + task.getStatus() + ")");
                        task.setStatus("Car wash complete");
                    }
                    @TaskDataLoader
                    public Soap loadSoap(Task task) {
                        System.out.println(" Loading soap");
                        return new Soap();
                    }
                    @TaskDataSaver
                    public void putCarToReadyQueue(Task task, Car car) {
                        System.out.println(" Putting car in ready queue");
                    }
                }
                """);
        writeSource(srcRoot, "Bar.java", """
                package demo.test;
                import com.doer.*;
                public class Bar {
                    @AcceptStatus("Driver wants a coffee")
                    public void takeACoffe(Task task, Driver driver) {
                        System.out.println("  Drinking coffee");
                        task.setStatus("Driver is happy with the coffee");
                    }
                    @TaskDataLoader
                    public Washer callFreeWasher(Task task) {
                        System.out.println(" Washer! Please help to new customer!");
                        return new Washer();
                    }
                    @TaskDataSaver
                    public void releaseFreeWasher(Task task, Washer washer) {
                        System.out.println(" Thank you, washer!");
                    }
                }
                """);
        writeSource(srcRoot, "CheckIn.java", """
                package demo.test;
                import com.doer.*;
                public class CheckIn {
                    @TaskDataLoader
                    public Car takeACar(Task task) {
                        System.out.println(" Taking customers car");
                        return new Car();
                    }
                    @TaskDataSaver
                    public void checkoutDriver(Task task, Driver driver) {
                        System.out.println(" Checkout.");
                    }
                }
                """);
        writeSource(srcRoot, "ExceptionMapper.java", """
                package demo.test;
                import com.doer.*;
                import jakarta.json.JsonObjectBuilder;
                public class ExceptionMapper {
                    @ExceptionDescriber
                    public void appendException1(Task task, Exception ex, JsonObjectBuilder builder) {
                        builder.add("appendException1", 1);
                    }
                    @ExceptionDescriber
                    public void appendRuntimeException2(Task task, RuntimeException ex, JsonObjectBuilder builder) {
                        builder.add("appendRuntimeException2", 2);
                    }
                }
                """);
    }

    /** Writes Main.java for the car wash classes; returns its expected output. */
    static String writeCarWashMain(Path srcRoot) throws Exception {
        writeSource(srcRoot, "Main.java", """
                package demo.test;
                import com.doer.*;
                public class Main {
                    public static void main(String[] args) throws Exception {
                        System.out.println("---main---");
                        var doer = new TestDoerService();
                        doer._inject_carWash(new CarWash());
                        doer._inject_bar(new Bar());
                        doer._inject_checkIn(new CheckIn());
                        doer._inject_car(new demo.test2.Car());

                        Task task = new Task();

                        System.out.println("Washing the car:");
                        task.setStatus("Car is ready to be washed");
                        doer.runTask(task);
                        System.out.println(task.getStatus());

                        System.out.println("Washing the Bus:");
                        task.setStatus("Bus came to the wash");
                        doer.runTask(task);
                        System.out.println(task.getStatus());

                        System.out.println("Taking a coffee:");
                        task.setStatus("Driver wants a coffee");
                        doer.runTask(task);
                        System.out.println(task.getStatus());

                        System.out.println("---end-of-main---");
                    }
                }
                """);
        return """
                ---main---
                Washing the car:
                 Taking customers car
                 Washer! Please help to new customer!
                 Loading soap
                  Washing the car (Car is ready to be washed)
                 Thank you, washer!
                 Putting car in ready queue
                Car wash complete
                Washing the Bus:
                 Taking customers car
                 Washer! Please help to new customer!
                 Loading soap
                  Washing the car (Bus came to the wash)
                 Thank you, washer!
                 Putting car in ready queue
                Car wash complete
                Taking a coffee:
                 Inviting driver
                  Drinking coffee
                 Checkout.
                Driver is happy with the coffee
                ---end-of-main---
                """;
    }
}
