name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B --color=always package
      - name: Tests Java17 jakarta 10.0.0
        run: mvn -B --color=always verify
      - name: Tests Java17 jakarta 8.0.0
        run: mvn -B --color=always -Dtest.doer.jakarta.version=8.0.0 verify
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Show java version
        run: java -version
      - name: Show mvn version
        run: mvn --version
      - name: Tests Java8 jakarta 8.0.0
        run: mvn -B --color=always -Dtest.doer.jakarta.version=8.0.0 verify
