name: Publish Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        default: '1.0.0'
        required: false
        type: string
      snapshot_version:
        description: 'Snapshot version (will be set in main branch after release is published)'
        default: '1.0.1-SNAPSHOT'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_CENTRAL_LOGIN
          server-password: MAVEN_CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Publish to Apache Maven Central
        run: mvn -B --color=always clean deploy -Prelease
        env:
          MAVEN_CENTRAL_LOGIN: ${{ secrets.MAVEN_CENTRAL_LOGIN }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
